name: Build Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u takemyoxygen --password-stdin
        docker build . --file Dockerfile --tag takemyoxygen/alt-pocket:$BUILD_NUMBER --build-arg BUILD_NUMBER=$BUILD_NUMBER --tag takemyoxygen/alt-pocket:latest
        if [ ${{github.ref}} = 'refs/heads/master' ]
        then
          docker push takemyoxygen/alt-pocket
        fi
