# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - alt-pocket

on:
  push:
    branches:
      - master

jobs:
  build-front-end:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
      with:
        node-version: '12'
    - run: |
        cd client
        npm ci --no-progress
        npm run build
    - uses: actions/upload-artifact@v1
      with:
        name: front-end-bundle
        path: client/dist

  build-and-deploy:
    runs-on: windows-latest
    needs: build-front-end

    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}

    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Build with dotnet
      run: dotnet build server/src/AltPocket.Web/AltPocket.Web.csproj --configuration Release --version-suffix ${{env.BUILD_NUMBER}}

    - name: dotnet publish
      run: dotnet publish server/src/AltPocket.Web/AltPocket.Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --version-suffix ${{env.BUILD_NUMBER}}


    - uses: actions/download-artifact@v1
      with:
        name: front-end-bundle
        path: ${{env.DOTNET_ROOT}}/myapp/wwwroot

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'alt-pocket'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_25a403f9e7584f07953af558d46ee20c }}
        package: ${{env.DOTNET_ROOT}}/myapp
